name: Zaraimandi Daily Email

on:
  schedule:
    # 12:00 UTC = 17:00 (5pm) Pakistan time (UTC+5)
    - cron: "0 12 * * *"
  workflow_dispatch: {}

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run daily email script
        env:
        PYTHONUNBUFFERED: "1"
        SMTP_USER: ${{ secrets.REPORT_SENDER_EMAIL }}
        SMTP_PASS: ${{ secrets.REPORT_SENDER_PASS }}
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: "465"
        REPORT_RECIPIENT_EMAIL: ${{ secrets.REPORT_RECIPIENT_EMAIL }}

         
        run: |
          python daily_email_runner.py

